export const LIST_COURSE_NOT_REGISTERED = "@registerCourseModalReducer/LIST_COURSE_NOT_REGISTERED"
export const LIST_COURSE_REGISTERED = "@registerCourseModalReducer/LIST_COURSE_REGISTERED"
export const LIST_COURSE_WAITING = "@registerCourseModalReducer/LIST_COURSE_WAITING"
export const COURSE_REGISTER = "@registerCourseModalReducer/COURSE_REGISTER"
export const CANCEL_REGISTER =  "@registerCourseModalReducer/CANCEL_REGISTER"